### PR TITLE
refactor: use list of generated recipes from jsonnet for build matrix

### PR DESCRIPTION
**Pull request by xynydev**
This generates the matrix of recipes to build automagically from the Jsonnet output, using GitHub Actions jobs. 

The commit history is a mess, but at least you can appreciate the struggle, and can of course squash it :)

### CODE REVIEW

**Comment by xynydev** [comment]
Scrap that, the files don't carry over...

**Comment by xynydev** [comment]
Aight, here's what should be a functional build: https://github.com/xynydev/Atomic-Studio/actions/runs/8492689295/job/23265954286

It's not the cleanest yet, but I may leave that as an excersize to the reader. I don't know if having to install jsonnet and generate the recipes multiple times is something that can be fixed here.

**Comment by tulilirockz** [comment]
LOL honestly LGTM!!!! ill be merging it fully cuz of the funny commit history

**Comment by xynydev** [comment]
Lol, I would have squashed the PR 100% of the time here, because the rest of the commits have no relation to anything in the message and such, and are all just trying to iterate and fix the thing that is described in the first commit and PR title.

**Pull request merged**
